/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define PORT_DFER_DFE_7_MASK 0x80u   /*!<@brief Digital Filter Enable Mask for item 7. */
#define PORT_DFER_DFE_8_MASK 0x0100u /*!<@brief Digital Filter Enable Mask for item 8. */
#define PORT_DFER_DFE_9_MASK 0x0200u /*!<@brief Digital Filter Enable Mask for item 9. */

/*! @name PORTE10 (number 4), D1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_D1_GPIO GPIOE                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_D1_GPIO_PIN_MASK (1U << 10U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_D1_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_D1_PIN 10U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_D1_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PORTE11 (number 3), D2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_D2_GPIO GPIOE                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_D2_GPIO_PIN_MASK (1U << 11U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_D2_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_D2_PIN 11U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_D2_PIN_MASK (1U << 11U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PORTB5 (number 18), D3
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_D3_GPIO GPIOB               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_D3_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_D3_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_D3_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_D3_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                   /* @} */

/*! @name PORTE8 (number 17), D4
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_D4_GPIO GPIOE               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_D4_GPIO_PIN_MASK (1U << 8U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_D4_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_D4_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_D4_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                   /* @} */

/*! @name PORTC9 (number 35), C2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_C2_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_C2_GPIO_PIN_MASK (1U << 9U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_C2_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_C2_PIN 9U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_C2_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                   /* @} */

/*! @name PORTC8 (number 36), C3
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_C3_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_C3_GPIO_PIN_MASK (1U << 8U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_C3_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_C3_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_C3_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                   /* @} */

/*! @name PORTA7 (number 37), C4
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_C4_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_C4_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_C4_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_C4_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_C4_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                   /* @} */

/*! @name PORTD4 (number 44), HIP_IDLE
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_HIP_IDLE_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_HIP_IDLE_GPIO_PIN_MASK (1U << 4U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_HIP_IDLE_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_HIP_IDLE_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_HIP_IDLE_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTA1 (number 49), HIP_CLK
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_HIP_CLK_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_HIP_CLK_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_HIP_CLK_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
